baseURL = 'https://www.rossknapman.com'
languageCode = 'en-gb'
title = 'Ross Knapman'
theme = "RossTheme"
relativeURLs = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    pre = "book"
    url="/publications"
    weight = 4
  [[menu.main]]
    name = "Notes"
    pre = "info"
    url="/notes/"
    weight = 5

[params]
  linkedin = "rossknapman97"
  github = "RossKnapman"