baseURL = 'https://www.rossknapman.com'
languageCode = 'en-gb'
title = 'Ross Knapman'
theme = "RossTheme"
relativeURLs = true
enableRobotsTXT = true
pluralizeListTitles = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    pre = "book"
    url="/publications"
    weight = 4
  [[menu.main]]
    name = "Notes"
    pre = "info"
    url="/notes/"
    weight = 5
  [[menu.main]]
    name = "Misc"
    pre = "archive"
    url="/misc/"
    weight=6

[markup]
  [markup.goldmark]
    # Allow rendering of raw HTML
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  
[params]
  linkedin = "rossknapman97"
  github = "RossKnapman"
  math = true